# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7963debfa6178e7cca577afb96adcb8aa5b4935a22dee03d29d2f80f1d15f12c90f3f4c770014038eb3cf7bacf38831d2ea840965f73f08b420464f9e1ea698

test:
  secret_key_base: 5620f034f6121f2a9ae5615fd208b0464de66c29fdbf0f34bf747e5fe2dcfc4472f6f9ca036377e9dddcc2c47cf618f15ed9ed320a101f12444e3608d035e671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
